# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Focus
    url: '/focus'
    weight: 20
    identifier: focus
  - name: Data Science
    url: '/focus/example/'
    weight: 100
    parent: focus
  - name: Data Quality
    url: '/focus/example/'
    weight: 80
    parent: focus
  - name: Data Observability
    url: '/focus/example/'
    weight: 60
    parent: focus
  - name: Data Discovery
    url: '/focus/example/'
    weight: 40
    parent: focus
  - name: Data Delivery
    url: '/focus/example/'
    weight: 20
    parent: focus
  - name: SE/DE dichotomy
    url: '/focus/example/'
    weight: 10
    parent: focus    
  - name: Blog
    url: '/post'
    weight: 30
  - name: Contact
    url: '/contact'
    weight: 60
